solution
mate-academy/js_promise_basic_DOM pull request #104
Opened 2021-04-18 20:58 UTC by Dinexpod

[DEMO LINK](https://Dinexpod.github.io/js_promise_basic_DOM/)

2021-04-19 09:22 UTC, vkryvytskyy requested changes

2021-04-19 09:22 UTC, vkryvytskyy commented on src/scripts/main.js
> +}, 3000);
А где промисы?)

2021-04-21 20:56 UTC, Dinexpod commented on src/scripts/main.js
> +}, 3000);
=)

2021-04-22 08:32 UTC, vkryvytskyy approved these changes

2026-05-10 22:13 UTC, closed without merging