solution
mate-academy/js_promise_basic_DOM pull request #398
Opened 2023-01-15 21:15 UTC by 1stIndominus

[DEMO LINK](https://1stIndominus.github.io/js_promise_basic_DOM/)

2023-01-16 18:07 UTC, polosanya requested changes
Let's try to pass the tests

2023-01-16 18:07 UTC, polosanya commented on src/scripts/main.js
> +  return new Promise((resolve) => {
Do you need function to create promise?
Just save the promise to some variable

2023-01-16 18:07 UTC, polosanya commented on src/scripts/main.js
> +const message = (className, text) => {
```suggestion
const showMessage = (className, text) => {
```
![image](https://user-images.githubusercontent.com/96409563/212742270-7aae8940-e8f5-4300-949e-7f8ee8bd3dfb.png)

2023-01-18 11:30 UTC, Anastasiia-Svintsova requested changes
Good! Fix one small comment, please

2023-01-18 11:30 UTC, Anastasiia-Svintsova commented on src/scripts/main.js
> +  .catch(error => showMessage('error-message', error));
You do the same for both promises here. Create a function for it, please

2023-01-19 09:41 UTC, polosanya approved these changes
Good job!

2023-01-19 09:41 UTC, polosanya commented on src/scripts/main.js
> +const promiseResult = (promise) => {
```suggestion
const handlePromises = (promise) => {
```

2023-12-06 14:28 UTC, closed without merging