solution
mate-academy/js_promise_basic_DOM pull request #857
Opened 2024-08-15 17:49 UTC by Fetrw

[DEMO LINK](https://Fetrw.github.io/js_promise_basic_DOM/)

2024-08-15 17:53 UTC, TarasHoliuk requested changes

2024-08-15 17:53 UTC, TarasHoliuk commented on src/scripts/main.js
> +    resolve();
```suggestion
    resolve('Promise was resolved!');
```
and get it as an argument in the `handleSuccess` function to use as text content

2024-08-16 09:38 UTC, volodymyr-soltys97 requested changes
Good job 👍 
Let's make your code better

2024-08-16 09:38 UTC, volodymyr-soltys97 commented on src/scripts/main.js
> +  document.body.appendChild(messageDiv);
Create a helper function for this logic and use it in two places

2024-08-18 10:49 UTC, vadiimvooo approved these changes
Well done

2026-01-16 17:45 UTC, closed without merging